development:
  adapter: postgresql
  encoding: unicode
  database: ddu8b7bhkk835m
  hostname: ec2-54-197-241-64.compute-1.amazonaws.com
  pool: 5
  username: dnvtkayjqbvxkj
  password: cUS72o9wtwoCWro9nui8Vshxw5
  port: 5432
  #adapter: sqlite3
  #database: db/test.sqlite3
  #pool: 5
  #timeout: 5000
test:
  adapter: postgresql
  encoding: unicode
  database: ddu8b7bhkk835m
  hostname: ec2-54-197-241-64.compute-1.amazonaws.com
  pool: 5
  username: dnvtkayjqbvxkj
  password: cUS72o9wtwoCWro9nui8Vshxw5
  port: 5432
production:
  adapter: postgresql
  encoding: unicode
  database: ddu8b7bhkk835m
  hostname: ec2-54-197-241-64.compute-1.amazonaws.com
  pool: 5
  username: dnvtkayjqbvxkj
  password: cUS72o9wtwoCWro9nui8Vshxw5
  port: 5432